### PR TITLE
Add Meakashi GOG

### PR DESCRIPTION
**Pull request by ItaloKnox**

### CODE REVIEW

**Comment by tellowkrinkle** [comment]
Looks fine, though wouldn't we want a Linux/Mac version of that as well?

**Comment by ItaloKnox** [comment]
Yeah... actually, we don't have one yet. We need someone with the game on Linux to get that.

**Comment by tellowkrinkle** [comment]
As it turns out, the `vanilla.7z` linked on the `ui-editing-scripts` repo still has the old file

Though you have to be careful because apparently they [messed with one of the assets](https://github.com/07th-mod/ui-editing-scripts/commit/691ae0c0d72e736d96cc64d037edf2fe202fe9c0) in the update
[Meakashi-UI_gog_mac.zip](https://github.com/07th-mod/python-patcher/files/3185314/Meakashi-UI_gog_mac.zip)

**Comment by ItaloKnox** [comment]
Can you check this out @enumag?

**Comment by enumag** [comment]
@ItaloKnox I'll when I get home.

**Comment by ItaloKnox** [comment]
I'll merge this since there's actually a demand for this fix right now in the Discord server.

**Pull request merged**
